spring:
  application:
    name: ship-it
  security:
    user:
      name: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}
      roles: ADMIN
app:
  sanity-checks-path: classpath:data/sanity-checks.json
